- id: '1601861290733'
  alias: Turn on lights in the morning
  description: ''
  trigger:
  - platform: time
    at: 06:30
  - platform: sun
    event: sunrise
    offset: -00:30:00
  condition: []
  action:
  - domain: light
    entity_id: light.dining_room_light
    device_id: 1bf4a797f96611eaa83ca33737892e40
    type: turn_on
    brightness_pct: 100
    flash: long
  mode: single
- id: '1601861512613'
  alias: Turn lights on in the evening
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  condition: []
  action:
  - scene: scene.lamps_on
  mode: single
- id: '1601861561681'
  alias: Turn lights off in the evening
  description: ''
  trigger:
  - platform: time
    at: '23:00'
  condition: []
  action:
  - scene: scene.lamps_off
  mode: single
- id: '1602948877563'
  alias: Everything off weeknight
  description: ''
  trigger:
  - platform: time
    at: '23:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - scene: scene.lamps_off
  - type: turn_off
    device_id: c533d733108c11eb8e12bd20fc718008
    entity_id: switch.esspresso_machine
    domain: switch
  - scene: scene.house_locked_up
  mode: single
- id: '1602948908812'
  alias: Everything off weekend
  description: ''
  trigger:
  - platform: time
    at: '23:30'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - scene: scene.lamps_off
  - type: turn_off
    device_id: c533d733108c11eb8e12bd20fc718008
    entity_id: switch.esspresso_machine
    domain: switch
  - scene: scene.house_locked_up
  mode: single
- id: '1602948968328'
  alias: Turn lights off weekend morning
  description: ''
  trigger:
  - platform: time
    at: 09:30
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - scene: scene.lamps_off
  mode: single
- id: '1602948993793'
  alias: Turn lights off weekday morning
  description: ''
  trigger:
  - platform: time
    at: 08:30
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - scene: scene.lamps_off
  mode: single
- id: '1602949139660'
  alias: Turn espresso maker on (weekdays)
  description: ''
  trigger:
  - platform: time
    at: 06:45
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - type: turn_on
    device_id: c533d733108c11eb8e12bd20fc718008
    entity_id: switch.esspresso_machine
    domain: switch
  mode: single
- id: '1602949162441'
  alias: Turn espresso maker on (weekend)
  description: ''
  trigger:
  - platform: time
    at: 07:15
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - type: turn_on
    device_id: c533d733108c11eb8e12bd20fc718008
    entity_id: switch.esspresso_machine
    domain: switch
  mode: single
- alias: homeassistant start-up
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.system_ready
  - service: input_boolean.turn_off
    entity_id: input_boolean.allow_automation_execution
  id: def09d88895949609b7fbbc6b4364391
- alias: open_zwave_network_down
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.ozw_network_status
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.allow_automation_execution
  id: 385ba8c3002d40128e13d8cdd91db476
- alias: open_zwave_network_up
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: binary_sensor.ozw_network_status
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.ozw_network_status
    state: 'on'
  action:
  - service: script.system_startup_cleanup
  id: 1c90aee2cfa44e859213900aa79a323a
- id: '1605425910532'
  alias: Tag Bedtime is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 0cd8f320-fdad-4bf7-a1ca-21b8fb4c6631
  condition: []
  action:
  - service: script.house_bedtime
    data: {}
  mode: single
- alias: Living Room Scene
  trigger:
    platform: state
    entity_id: input_select.living_room_scene
  action:
  - service: scene.turn_on
    data_template:
      entity_id: scene.living_room_{{ states.input_select.living_room_scene.state
        | replace(' ', '_') | lower | string }}
  id: 121488b9efeb4d52a40be40b23d6eb2a
- id: '1609620140039'
  alias: Notify washing machine done
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: 0ba86b704c7f11eb98d5e3f83f0e6148
    entity_id: sensor.washer_outlet_power
    domain: sensor
    below: 30
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: notify.pushover_notify_hass
    data:
      message: Washing machine is done!
  mode: single
