# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  unit_system: imperial
  time_zone: !secret home_time_zone
  internal_url: !secret server_address
  packages: !include_dir_named includes
  allowlist_external_dirs: [/config/]
  #customize: !include customize.yaml

# Automation
automation: !include automations.yaml

browser_mod:

# Cover MyQ garage doors and openers
cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password

# Ecowitt weather station
ecowitt:
  port: !secret ecowitt_port
  barounit: metric
  windunit: imperial
  rainunit: imperial
  windchillunit: hybrid

# Google calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# Groups
group: !include groups.yaml

# Light Groups
light: !include light-groups.yaml

# Enable logging controls
logger:
  default: error
  logs:
    # Enable warn logging for Lock Manager
    custom_components.lock-manager: warn

# Pushover notifications
notify:
  - name: pushover_notify_hass
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

# Scenes
scene: !include scenes.yaml

# Scripts
script: !include scripts.yaml

# Text to speech
tts:
  - platform: google_translate

# Belkin Wemo
wemo:
  discovery: true

# Lovelace dashboards
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/compass-card/compass-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-hui-element/hui-element.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url:  /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js
      type: module
  # Add yaml dashboards
  dashboards:
    locks-yaml:
      mode: yaml
      title: Locks
      icon: mdi:door-closed-lock
      filename: ui-lock-manager.yaml
      show_in_sidebar: true
      require_admin: true
    tablet-yaml:
      mode: yaml
      title: Tablet
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
      filename: ui-tablet.yaml
    weather-yaml:
      mode: yaml
      title: Weather
      icon: mdi:weather-sunny
      show_in_sidebar: true
      filename: ui-weather.yaml
    test-yaml:
      mode: yaml
      title: Test
      icon: mdi:test-tube
      show_in_sidebar: true
      filename: ui-test.yaml