views:
  - panel: true
    cards:
      - type: markdown
        content: >
          <span>{{ states('sensor.time') }}</span>

          <font color='#6a7377'><b>{{ states('sensor.sidebar_day') }}</b><br>
          <b>{{ states('sensor.sidebar_date') }}</b> </font><br>

          <b>{{ states('sensor.sidebar_greeting') }}</b>