views:
  - panel: true
    cards:
      - title: 8" Tablet
        type: custom:layout-card
        layout: vertical
        column_width: [21%, 79%]
        column_num: 2
        cards:
          - type: markdown
            class: sidebar
            style: |
              .sidebar {
                font-size: 1.5vw;
                font-weight: 300;
                opacity: 0.75;
              }
            content: >
              <span>{{ states('sensor.time') }}</span>

              <font color='#6a7377'><b>{{ states('sensor.sidebar_day') }}</b><br>
              <b>{{ states('sensor.sidebar_date') }}</b> </font><br>

              <b>{{ states('sensor.sidebar_greeting') }}</b>

              <b>{{ states('sensor.sidebar_active') }}</b>

              <font color='#6a7377'>
              <b>{{ states('sensor.sidebar_vacuum') }}</b>
              </font>
          - type: horizontal-stack
            cards:
              - type: button
                icon: mdi:robot-vacuum
                show_state: false
                tap_action: !include popup/sidebar_vacuum.yaml
                icon_height: 64
              - type: button
                icon: mdi:information-outline
                show_state: false
                tap_action: !include popup/sidebar_homeassistant.yaml
                icon_height: 64
              - type: button
                icon: mdi:nas
                show_state: false
                icon_height: 64
          - break
          - type: custom:layout-card
            layout: horizontal
            column_width: [33%, 34%, 33%]
            column_num: 3
            cards:
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: >
                      INDOOR LIGHTS
                  - type: entities
                    show_header_toggle: false
                    entities:
                      - entity: light.dining_room_light
                        name: Buffet
                      - entity: light.living_room_lights
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: >
                      LIVING ROOM
                  - type: entities
                    show_header_toggle: false
                    entities:
                      - entity: light.end_table_lamp
                        name: End Table
                      - entity: light.floor_lamp
                        name: Floor
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: >
                      MASTER BEDROOM
                  - type: entities
                    show_header_toggle: false
                    entities:
                      - entity: sensor.temperature_4
                        name: Temp
                      - entity: sensor.placeholder
          - type: custom:layout-card
            layout: horizontal
            column_width: [33%, 34%, 33%]
            column_num: 3
            cards:
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: >
                      GARAGE
                  - type: entities
                    show_header_toggle: false
                    entities:
                      - entity: sensor.temperature_1
                        name: Temp
                      - entity: sensor.temperature_2
                        name: Wine Fridge
                      - entity: light.wine_fridge
                        name: Wine Fridge
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: >
                      KITCHEN
                  - type: entities
                    show_header_toggle: false
                    entities:
                      - entity: sensor.temperature_3
                        name: Temp
                      - entity: switch.leviton_dzpa1_2bw_plug_in_outlet_switch
                        name: Espresso Machine                        
                      - entity: sensor.placeholder
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: >
                      DOORS
                  - type: entities
                    show_header_toggle: false
                    entities:
                      # - entity: lock.schlage_locked_front_door
                      #   name: Front
                      - entity: sensor.placeholder
                      - entity: sensor.placeholder
                      - entity: sensor.placeholder
          - type: custom:layout-card
            layout: horizontal
            column_width: [33%, 34%, 33%]
            column_num: 3
            cards:
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: >
                      OUTSIDE
                  - type: entities
                    show_header_toggle: false
                    entities:
                      - entity: sensor.outdoor_temperature
                        name: Temp
                      - entity: sensor.humidity
                        name: Hunidity
                      - entity: sensor.placeholder
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: >
                      PLEX
                  - type: entities
                    show_header_toggle: false
                    entities:
                      - entity: sensor.placeholder
                      - entity: sensor.placeholder
                      - entity: sensor.placeholder
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: >
                      FORECAST
                  - type: entities
                    show_header_toggle: false
                    entities:
                      - entity: sensor.placeholder
                      - entity: sensor.placeholder
                      - entity: sensor.placeholder
