views:
  - panel: true
    cards:
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - type: markdown
                content: >
                  <span>{{ states('sensor.time') }}</span>

                  <font color='#6a7377'><b>{{ states('sensor.sidebar_day') }}</b><br>
                  <b>{{ states('sensor.sidebar_date') }}</b> </font><br>

                  <b>{{ states('sensor.sidebar_greeting') }}</b>

                  <b>{{ states('sensor.sidebar_active') }}</b>
              - type: horizontal-stack
                cards:
                  - type: button
                    icon: mdi:robot-vacuum
                    show_state: false
                    icon_height: 128
                    tap_action: !include popup/sidebar_vacuum.yaml
                  - type: button
                    icon: mdi:information-outline
                    show_state: false
                    icon_height: 128
                  - type: button
                    icon: mdi:nas
                    show_state: false
                    icon_height: 128

          - type: markdown
            content: >
              Lorem ipsum dolor sit amun.