views:
  - panel: true
    cards:
      - title: 8" Tablet
        type: custom:layout-card
        layout: vertical
        column_width: [21%, 79%]
        column_num: 2
        cards:
          - type: markdown
            class: sidebar
            style: |
              .sidebar {
                font-size: 1.5vw;
                font-weight: 300;
                opacity: 0.75;
              }
            content: >
              <span>{{ states('sensor.time') }}</span>

              <font color='#6a7377'><b>{{ states('sensor.sidebar_day') }}</b><br>
              <b>{{ states('sensor.sidebar_date') }}</b> </font><br>

              <b>{{ states('sensor.sidebar_greeting') }}</b>

              <b>{{ states('sensor.sidebar_active') }}</b>

              <font color='#6a7377'>
              <b>{{ states('sensor.sidebar_vacuum') }}</b>
              </font>
          - type: horizontal-stack
            cards:
              - type: button
                icon: mdi:robot-vacuum
                show_state: false
                tap_action: !include popup/sidebar_vacuum.yaml
                icon_height: 64
              - type: button
                icon: mdi:information-outline
                show_state: false
                tap_action: !include popup/sidebar_homeassistant.yaml
                icon_height: 64
              - type: button
                icon: mdi:nas
                show_state: false
                icon_height: 64
          - break
          - type: custom:layout-card
            layout: horizontal
            column_width: [33%, 34%, 33%]
            column_num: 3
            cards:
              - type: custom:mini-graph-card
                name: Outside
                entities:
                  - sensor.outdoor_temperature
                    show_state: true
                  - sensor.humidity
                    show_state: true
                    y_axis: true
                show: labels
              - type: custom:mini-graph-card
                name: Garage
                entities:
                  - sensor.temperature_1
                    show_state: true
                  - sensor.humidity_1
                    show_state: true
                    y_axis: true
                show: labels
              - type: custom:mini-graph-card
                name: Wine
                entities:
                  - sensor.temperature_2
                    show_state: true
                  - sensor.humidity_2
                    show_state: true
                    y_axis: true
                show: labels
          - break
          - type: custom:layout-card
            layout: horizontal
            column_width: [33%, 34%, 33%]
            column_num: 3
            cards:
              - type: custom:mini-graph-card
                name: Atrium
                entities:
                  - sensor.indoor_temperature
                    show_state: true
                  - sensor.indoor_humidity
                    show_state: true
                    y_axis: true
                show: labels
              - type: custom:mini-graph-card
                name: Kitchen
                entities:
                  - sensor.temperature_3
                    show_state: true
                  - sensor.humidity_3
                    show_state: true
                    y_axis: true
                show: labels
              - type: custom:mini-graph-card
                name: Master Bedroom
                entities:
                  - sensor.temperature_4
                    show_state: true
                  - sensor.humidity_4
                    show_state: true
                    y_axis: true
                show: labels
