views:
  - panel: true
    cards:
      - title: 8" Tablet
        type: custom:layout-card
        layout: vertical
        column_width: [21%, 79%]
        column_num: 2
        cards:
          - type: markdown
            class: sidebar
            style: |
              .sidebar {
                font-size: 1.5vw;
                font-weight: 300;
                opacity: 0.75;
              }
            content: >
              <span>{{ states('sensor.time') }}</span>

              <font color='#6a7377'><b>{{ states('sensor.sidebar_day') }}</b><br>
              <b>{{ states('sensor.sidebar_date') }}</b> </font><br>

              <b>{{ states('sensor.sidebar_greeting') }}</b>

              <b>{{ states('sensor.sidebar_active') }}</b>

              <font color='#6a7377'>
              <b>{{ states('sensor.sidebar_vacuum') }}</b>
              </font>
          - type: horizontal-stack
            cards:
              - type: button
                icon: mdi:robot-vacuum
                show_state: false
                tap_action: !include popup/sidebar_vacuum.yaml
                icon_height: 64
              - type: button
                icon: mdi:information-outline
                show_state: false
                tap_action: !include popup/sidebar_homeassistant.yaml
                icon_height: 64
              - type: button
                icon: mdi:nas
                show_state: false
                icon_height: 64
          - break
          - type: custom:layout-card
            layout: horizontal
            column_width: [33%, 34%, 33%]
            column_num: 3
            cards:
              - type: custom:mini-graph-card
                name: Outside
                entities:
                  - entity: sensor.outdoor_temperature
                    name: Temp
                    show_state: true
                  - entity: sensor.humidity
                    name: Humidity
                    show_state: true
                    y_axis: secondary
                show:
                  labels: true
                  labels_secondary: true
              - type: custom:mini-graph-card
                name: Garage
                entities:
                  - entity: sensor.temperature_1
                    name: Temp
                    show_state: true
                  - entity: sensor.humidity_1
                    name: Humidity
                    show_state: true
                    y_axis: secondary
                show:
                  labels: true
                  labels_secondary: true
              - type: custom:mini-graph-card
                name: Wine
                entities:
                  - entity: sensor.temperature_2
                    name: Temp
                    show_state: true
                  - entity: sensor.humidity_2
                    name: Humidity
                    show_state: true
                    y_axis: secondary
                show:
                  labels: true
                  labels_secondary: true
              - break
              - type: custom:mini-graph-card
                name: Atrium
                entities:
                  - entity: sensor.indoor_temperature
                    name: Temp
                    show_state: true
                  - entity: sensor.indoor_humidity
                    name: Humidity
                    show_state: true
                    y_axis: secondary
                show:
                  labels: true
                  labels_secondary: true
              - type: custom:mini-graph-card
                name: Kitchen
                entities:
                  - entity: sensor.temperature_3
                    name: Temp
                    show_state: true
                  - entity: sensor.humidity_3
                    name: Humidity
                    show_state: true
                    y_axis: secondary
                show:
                  labels: true
                  labels_secondary: true
              - type: custom:mini-graph-card
                name: Master Bedroom
                entities:
                  - entity: sensor.temperature_4
                    name: Temp
                    show_state: true
                  - entity: sensor.humidity_4
                    name: Humidity
                    show_state: true
                    y_axis: secondary
                show:
                  labels: true
                  labels_secondary: true
              - break
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: >
                      Wind
                  - type: entities
                    show_header_toggle: false
                    entities:
                      - entity: sensor.weather_wind_direction
                        name: Direction
                      - entity: sensor.wind_speed
                        name: Speed
                      - entity: sensor.wind_gust
                        name: Gust
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: >
                      Rainfall
                  - type: entities
                    show_header_toggle: false
                    entities:
                      - entity: sensor.hourly_rain_rate
                        name: Rate / hr
                      - entity: sensor.daily_rain_rate
                        name: Daily
