homeassistant:
  customize:
      ##########
      # Home Assistant
      ##########      
      hass_version:
        icon_template: mdi:home-assistant
        friendly_name_template: >
          Installed {{ states('sensor.hass_version_installed') }}
        value_template: >
          {{ 'Latest' if states('sensor.hass_version_installed') == 
          states('sensor.hass_version_latest') else states('sensor.hass_version_latest') }}

      home_assistant_v2_db:
        friendly_name: Database
        icon: mdi:database

      home_assistant_log:
        friendly_name: Log file
        icon: mdi:file-document
