sensor:
  ####################################################
  #                                                  #
  #                     SENSORS                      #
  #                                                  #
  ####################################################
  - platform: time_date
    display_options:
      ['time', 'date']

  ####################################################
  #                                                  #
  #                     TEMPLATE                     #
  #                                                  #
  ####################################################
  - platform: template
    sensors:
      sidebar_day:
        icon_template: mdi:calendar
        value_template: >
          {% set weekday = as_local(states.sensor.date.last_changed).strftime('%w') | int %}
          {% set days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %}
          {{ days[weekday - 1] }}

      sidebar_date:
        icon_template: mdi:calendar
        value_template: >
          {% set month = as_local(states.sensor.date.last_changed).strftime('%m') | int %}
          {% set day = as_local(states.sensor.date.last_changed).strftime('%d') | int %}
          {% set months = ['January', 'February', 'March', 'April', 'May', 'June', 
          'July', 'August', 'September', 'October', 'November', 'December'] %}
          {{ day }} {{ months[month - 1] }}

      sidebar_greeting:
        value_template: >
          {% set time = as_timestamp(states.sensor.time.last_changed | as_local) | timestamp_custom('%H') | int %}
          {% if time <= 1 %} Good night {{'\U0001F611'}}
          {% elif time <= 3 %} Good night {{'\U0001F62A'}}
          {% elif time <= 5 %} Good night {{'\U0001F634'}}
          {% elif time <= 7 %} Good morning {{'\U0001F4A9'}}
          {% elif time <= 9 %} Good morning {{'\u2615\uFE0F'}}
          {% elif time <= 10 %} Good morning {{'\U0001F642'}}
          {% elif time <= 13 %} Good afternoon {{'\U0001F60A'}}
          {% elif time <= 15 %} Good afternoon {{'\U0001F60E'}}
          {% elif time <= 17 %} Good afternoon {{'\U0001F44B\U0001F3FB'}}
          {% elif time <= 19 %} Good evening {{'\U0001F44B\U0001F3FB'}}
          {% elif time <= 22 %} Good evening {{'\U0001F60C'}}
          {% elif time <= 23 %} Good evening {{'\U0001F974'}}
          {% else %} Good evening {{'\U0001F974'}}
          {% endif %}
