sensor:
  ##########
  # SENSORS
  ##########
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
      - /config/home-assistant.log

  platform: moon

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: swap_use_percent
      - type: processor_use

  - platform: time_date
    display_options:
      ['time', 'date']

  - platform: uptime
    unit_of_measurement: minutes

  - platform: version
    name: hass_version_installed

  - platform: version
    name: hass_version_latest
    source: docker

  - platform: version
    name: hass_version_latest_beta
    beta: true
    source: docker

  ##########
  # TEMPLATES
  ##########
  - platform: template
    sensors:
      ##########
      # Information
      ##########
      hass_uptime:
        friendly_name: Last restart
        icon_template: mdi:update
        value_template: >
          {% set uptime = states('sensor.uptime') | float %}
          {% if uptime < 1 %} {{ (uptime * 60) | int }} seconds ago
          {% elif uptime | int == 1 %} 1 minute ago
          {% elif uptime | int > 1 %}
            {% if uptime | int < 60 %} {{ uptime | int }} minutes ago
            {% elif uptime | int / 60 == 24 %} {{ (uptime | int / 60 / 24) | int }} day ago
            {% elif uptime | int / 60 >= 24 %} {{ (uptime | int / 60 / 24) | int }} days ago
            {% elif uptime | int >= 60 and uptime | int < 120 %} {{ (uptime | int / 60) | int }} an hour ago
            {% elif uptime | int >= 120 %} {{ (uptime | int / 60) | int }} hours ago
            {% endif %}
          {% endif %}

      hass_version:
        icon_template: mdi:home-assistant
        friendly_name_template: >
          Installed {{ states('sensor.hass_version_installed') }}
        value_template: >
          {{ 'Latest' if states('sensor.hass_version_installed') == 
          states('sensor.hass_version_latest') else states('sensor.hass_version_latest') }}

      placeholder:
        value_template: ' '

      ##########
      # Sidebar
      ##########      
      sidebar_day:
        icon_template: mdi:calendar
        value_template: >
          {% set weekday = as_local(states.sensor.date.last_changed).strftime('%w') | int %}
          {% set days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %}
          {{ days[weekday - 1] }}

      sidebar_date:
        icon_template: mdi:calendar
        value_template: >
          {% set month = as_local(states.sensor.date.last_changed).strftime('%m') | int %}
          {% set day = as_local(states.sensor.date.last_changed).strftime('%d') | int %}
          {% set months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] %}
          {{ day }} {{ months[month - 1] }}

      sidebar_greeting:
        value_template: >
          {% set time = as_timestamp(states.sensor.time.last_changed | as_local) | timestamp_custom('%H') | int %}
          {% if time < 5 %} Good night
          {% elif time < 12 %} Good morning
          {% elif time < 17 %} Good afternoon
          {% elif time < 19 %} Good evening
          {% elif time < 22 %} Good night
          {% else %} Good evening
          {% endif %}

      sidebar_active:
        value_template: >
          {% set lights = [states.light.dining_room_light, states.light.end_table_lamp, states.light.floor_lamp, states.light.wine_fridge] %}
          {% set lights_on = lights | selectattr('state','eq','on') | list %}
          {% set lights_name = lights | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}

          {% set switches = [states.switch.leviton_dzpa1_2bw_plug_in_outlet_switch] %}
          {% set switches_on = switches | selectattr('state','eq','on') | list %} 
          {% set switches_name = switches | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}

          {% if (lights_on | length == 0) and (switches_on | length == 1) %} 
          {{ switches_name }} is on

          {% elif (lights_on | length == 0) and (switches_on | length > 1) %} 
          {{ switches_name | regex_replace(',([^,]*)$',' and\\1') }} are on

          {% elif (lights_on | length == 1) and (switches_on | length == 1) %}
          {{ lights_name }} and {{switches_name }} are on

          {% elif (lights_on | length == 1) and (switches_on | length > 1) %}
          {{ lights_name }}, {{ switches_name | regex_replace(',([^,]*)$',' and\\1') }} are on

          {% elif (lights_on | length > 1) and (switches_on | length == 1) %}
          {{ lights_on | length }} lights and {{ switches_name }} are on

          {% elif (lights_on | length > 1) and (switches_on | length > 1) %}
          {{ lights_on | length }} lights, {{ switches_name | regex_replace(',([^,]*)$',' and\\1') }} are on

          {% elif (lights_on | length == 1) and (switches_on | length == 0) %}
          {{ lights_name }} is on

          {% elif (lights_on | length > 1) and (switches_on | length == 0) %}
          {{ lights_on | length}} lights are on

          {% else %} 
          <font color='#6a7377'>Everything is off</font> 
          {% endif %}

      sidebar_vacuum:
        value_template: >
          {% set entity_id = 'vacuum.david' %}
          {% if is_state(entity_id, 'cleaning') %} David is cleaning
          {% elif is_state(entity_id, 'returning') %} David is done
          {% endif %}

      ##########
      # Vacuum
      ##########
      vacuum_cleaned_area:
        value_template: >
          {% set entity_id = 'vacuum.david' %}
          {% if is_state(entity_id, 'cleaning') %} Cleaned: {{ state_attr('vacuum.david', 'cleaned_area') }} ft^2
          {% elif is_state(entity_id, 'returning') %} Cleaned: {{ state_attr('vacuum.david', 'cleaned_area') }} ft^2
          {% endif %}

      vacuum_cleaning_time:
        value_template: >
          {% set entity_id = 'vacuum.david' %}
          {% if is_state(entity_id, 'cleaning') %} Cleaning time: {{ state_attr('vacuum.david', 'cleaning_time') }} mins
          {% elif is_state(entity_id, 'returning') %} Cleaning time: {{ state_attr('vacuum.david', 'cleaning_time') }} mins
          {% endif %}
