sensor:
  ####################################################
  #                                                  #
  #                     TEMPLATE                     #
  #                                                  #
  ####################################################
  - platform: template
  sensors:
    sidebar_day:
      icon_template: mdi:calendar
      value_template: >
        {% set weekday = as_local(states.sensor.date.last_changed).strftime('%w') | int %}
        {% set days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %}
        {{ days[weekday - 1] }}

    sidebar_date:
      icon_template: mdi:calendar
      value_template: >
        {% set month = as_local(states.sensor.date.last_changed).strftime('%m') | int %}
        {% set day = as_local(states.sensor.date.last_changed).strftime('%d') | int %}
        {% set months = ['January', 'February', 'March', 'April', 'May', 'June', 
        'July', 'August', 'September', 'October', 'November', 'December'] %}
        {{ day }} {{ months[month - 1] }}
