sensor:
  ####################################################
  #                                                  #
  #                     SENSORS                      #
  #                                                  #
  ####################################################
  - platform: time_date
    display_options:
      ['time', 'date']

  ####################################################
  #                                                  #
  #                     TEMPLATE                     #
  #                                                  #
  ####################################################
  - platform: template
    sensors:
      sidebar_day:
        icon_template: mdi:calendar
        value_template: >
          {% set weekday = as_local(states.sensor.date.last_changed).strftime('%w') | int %}
          {% set days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %}
          {{ days[weekday - 1] }}

      sidebar_date:
        icon_template: mdi:calendar
        value_template: >
          {% set month = as_local(states.sensor.date.last_changed).strftime('%m') | int %}
          {% set day = as_local(states.sensor.date.last_changed).strftime('%d') | int %}
          {% set months = ['January', 'February', 'March', 'April', 'May', 'June', 
          'July', 'August', 'September', 'October', 'November', 'December'] %}
          {{ day }} {{ months[month - 1] }}

      sidebar_greeting:
        value_template: >
          {% set time = as_timestamp(states.sensor.time.last_changed | as_local) | timestamp_custom('%H') | int %}
          {% if time <= 1 %} Good night
          {% elif time <= 3 %} Good night
          {% elif time <= 5 %} Good night
          {% elif time <= 7 %} Good morning
          {% elif time <= 9 %} Good morning
          {% elif time <= 10 %} Good morning
          {% elif time <= 13 %} Good afternoon
          {% elif time <= 15 %} Good afternoon
          {% elif time <= 17 %} Good afternoon
          {% elif time <= 19 %} Good evening
          {% elif time <= 22 %} Good evening
          {% elif time <= 23 %} Good evening
          {% else %} Good evening
          {% endif %}

      sidebar_active:
        value_template: >
          {% set lights = [states.light.dining_room_light, states.light.end_table_lamp, states.light.floor_lamp] %}
          {% set lights_on = lights | selectattr('state','eq','on') | list %}
          {% set lights_name = lights | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}

          {% set switches = [switch.leviton_dzpa1_2bw_plug_in_outlet_switch] %}
          {% set switches_on = switches | selectattr('state','eq','on') | list %} 
          {% set switches_name = switches | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}

          {% if (lights_on | length == 0) and (switches_on | length > 0) %} 
          {{ switches_name | regex_replace(',([^,]*)$',' och\\1') }} är på

          {% elif (lights_on | length == 1) and (switches_on | length == 1) %}
          {{ lights_name }} och {{switches_name }} är på

          {% elif (lights_on | length == 1) and (switches_on | length > 1) %}
          {{ lights_name }}, {{ switches_name | regex_replace(',([^,]*)$',' och\\1') }} är på

          {% elif (lights_on | length > 1) and (switches_on | length == 1) %}
          {{ lights_on | length }} lampor och {{ switches_name }} är på

          {% elif (lights_on | length > 1) and (switches_on | length > 1) %}
          {{ lights_on | length }} lampor, {{ switches_name | regex_replace(',([^,]*)$',' och\\1') }} är på

          {% elif (lights_on | length == 1) and (switches_on | length == 0) %}
          {{ lights_name }} är på

          {% elif (lights_on | length > 1) and (switches_on | length == 0) %}
          {{ lights_on | length}} lampor är på

          {% else %} 
          <font color='#6a7377'>Everything is off</font> 
          {% endif %}
